port: 7880
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50050
  use_external_ip: false
  node_ip: 192.168.178.60 # TODO;
keys:
  devkey: devsecret
logging:
  json: false
  level: info
